secret_key: "COMP9900_Nullbody"

smtp:
  host: smtp-mail.outlook.com
  user: no-reply.comp9900_nullbody@outlook.com
  password: asdfg987321
  port: 587

redis:
  host: singapore-redis.render.com
  user: red-cnnh3udjm4es7395e4vg
  password: 747IVoMENPI29aHHkEQZChywvVwfelR3
  port: 6379

# sql type: "mysql" or "postgresql"
sql:
  # # localhost - mysql
  # type: mysql
  # host: localhost
  # user: yst990102
  # password: zxcvb987321
  # name: comp9900
  # port: 3306

  # # localhostz - postgresql
  # type: postgresql
  # host: localhost
  # user: yst990102
  # password: zxcvb987321
  # name: comp9900
  # port: 5432

  # # Render - postgresql - external
  # type: postgresql
  # host: dpg-cnfh5cta73kc73936pu0-a.singapore-postgres.render.com
  # user: yst990102
  # password: uIndhibQMr94jnGtIDj3Dw7fQpFA5aSD
  # name: comp9900
  # port: 5432

  # Render - postgresql - internal
  type: postgresql
  host: dpg-cnfh5cta73kc73936pu0-a
  user: yst990102
  password: uIndhibQMr94jnGtIDj3Dw7fQpFA5aSD
  name: comp9900
  port: 5432
