secret_key: "COMP9900_Nullbody"

smtp:
  host: smtp.gmail.com
  user: noreply.comp9900nullbody@gmail.com
  password: wgeuoicxihvgwfeh
  port: 587

# sql type: "mysql" or "postgresql"
database:
  # # localhost - mysql
  # type: mysql
  # host: localhost
  # user: yst990102
  # password: zxcvb987321
  # name: comp9900
  # port: 3306

  # # localhostz - postgresql
  # type: postgresql
  # host: localhost
  # user: yst990102
  # password: zxcvb987321
  # name: comp9900
  # port: 5432

  # # Render - postgresql - external
  # type: postgresql
  # host: dpg-cnfh5cta73kc73936pu0-a.singapore-postgres.render.com
  # user: yst990102
  # password: uIndhibQMr94jnGtIDj3Dw7fQpFA5aSD
  # name: comp9900
  # port: 5432

  # Render - postgresql - internal
  type: postgresql
  host: dpg-cnfh5cta73kc73936pu0-a
  user: yst990102
  password: uIndhibQMr94jnGtIDj3Dw7fQpFA5aSD
  name: comp9900
  port: 5432
