DROP TABLE IF EXISTS countries;
CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255)
);

INSERT INTO countries (name) VALUES
(''),
('Antigua and Barbuda'),
('Argentina'),
('Australia'),
('Austria'),
('Bahamas, The'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belgium'),
('Bermuda'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('British Virgin Islands'),
('Bulgaria'),
('Burundi'),
('Cambodia'),
('Canada'),
('Cayman Islands'),
('Chile'),
('China'),
('Colombia'),
('Cote d''Ivoire'),
('Croatia'),
('Curacao'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Ecuador'),
('Egypt, Arab Rep.'),
('Estonia'),
('Faroe Islands'),
('Finland'),
('France'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar'),
('Greece'),
('Hong Kong SAR, China'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Ireland'),
('Isle of Man'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Korea, Rep.'),
('Kuwait'),
('Latvia'),
('Lebanon'),
('Liberia'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macao SAR, China'),
('Malawi'),
('Malaysia'),
('Malta'),
('Marshall Islands'),
('Mauritius'),
('Mexico'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Namibia'),
('Netherlands'),
('New Zealand'),
('Nigeria'),
('North Macedonia'),
('Norway'),
('Oman'),
('Pakistan'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('Romania'),
('Russian Federation'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Singapore'),
('Slovak Republic'),
('Slovenia'),
('South Africa'),
('Spain'),
('Sri Lanka'),
('Sweden'),
('Switzerland'),
('Taiwan, China'),
('Tanzania'),
('Thailand'),
('Togo'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Venezuela, RB'),
('Vietnam'),
('Virgin Islands (U.S.)'),
('Zambia'),
('Zimbabwe');
