DROP TABLE IF EXISTS indicator_weights;

CREATE TABLE indicator_weights(
    framework_id INT not NULL,
    indicator_id INT Not NULL,
    indicator_name VARCHAR(255) not NULL,
    indicator_weight FLOAT not NULL

);

INSERT INTO indicator_weights(framework_id,indicator_id,indicator_name,indicator_weight)VALUES
(1,1,'Carbon Emissions and Air Pollutants',0.4),
(1,2,'Energy Consumption and Electricity Consumption',0.3),
(1,3,'Renewable Energy and Waste',0.6),
(1,4,'Water Withdrawal and Sustainable Practices',0.4),
(1,5,'Biodiversity and Climate Change Management',0.8),
(1,6,'Human Rights and Gender Equality',0.3),
(1,7,'Employee Well-being and Safety',0.5),
(1,8,'Ethical Practices and Compliance',0.7),
(1,9,'Certifications',0.5),
(1,10,'Labor Relations and Employee Engagement',0.5),
(1,11,'Corporate Social Responsibility (CSR) and Diversity',0.3),
(1,12,'Board Structure and Independence',0.8),
(1,13,'Audit, Compliance, and Risk Management',0.1),
(1,14,'Compensation Policy and Performance Incentives',0.9),
(1,15,'Transparency and Accountability',0.4),
(1,16,'Shareholder Rights and Corporate Governance',0.5),
(2,1,'Carbon Emissions and Air Pollutants',0.1),
(2,2,'Energy Consumption and Electricity Consumption',0.9),
(2,3,'Renewable Energy and Waste',0.3),
(2,4,'Water Withdrawal and Sustainable Practices',0.5),
(2,5,'Biodiversity and Climate Change Management',0.8),
(2,6,'Human Rights and Gender Equality',0.6),
(2,7,'Employee Well-being and Safety',0.9),
(2,8,'Ethical Practices and Compliance',0.7),
(2,9,'Certifications',0.3),
(2,10,'Labor Relations and Employee Engagement',0.2),
(2,11,'Corporate Social Responsibility (CSR) and Diversity',0.2),
(2,12,'Board Structure and Independence',0.8),
(2,13,'Audit, Compliance, and Risk Management',0.1),
(2,14,'Compensation Policy and Performance Incentives',0.7),
(2,15,'Transparency and Accountability',0.8),
(2,16,'Shareholder Rights and Corporate Governance',0.5),
(3,1,'Carbon Emissions and Air Pollutants',0.9),
(3,2,'Energy Consumption and Electricity Consumption',0.1),
(3,3,'Renewable Energy and Waste',0.6),
(3,4,'Water Withdrawal and Sustainable Practices',0.6),
(3,5,'Biodiversity and Climate Change Management',0.5),
(3,6,'Human Rights and Gender Equality',0.3),
(3,7,'Employee Well-being and Safety',0.4),
(3,8,'Ethical Practices and Compliance',0.1),
(3,9,'Certifications',0.8),
(3,10,'Labor Relations and Employee Engagement',0.7),
(3,11,'Corporate Social Responsibility (CSR) and Diversity',0.7),
(3,12,'Board Structure and Independence',0.8),
(3,13,'Audit, Compliance, and Risk Management',0.1),
(3,14,'Compensation Policy and Performance Incentives',0.4),
(3,15,'Transparency and Accountability',0.4),
(3,16,'Shareholder Rights and Corporate Governance',0.5),
(4,1,'Carbon Emissions and Air Pollutants',0.4),
(4,2,'Energy Consumption and Electricity Consumption',0.3),
(4,3,'Renewable Energy and Waste',0.3),
(4,4,'Water Withdrawal and Sustainable Practices',0.6),
(4,5,'Biodiversity and Climate Change Management',0.7),
(4,6,'Human Rights and Gender Equality',0.4),
(4,7,'Employee Well-being and Safety',0.4),
(4,8,'Ethical Practices and Compliance',0.9),
(4,9,'Certifications',0.2),
(4,10,'Labor Relations and Employee Engagement',0.3),
(4,11,'Corporate Social Responsibility (CSR) and Diversity',0.6),
(4,12,'Board Structure and Independence',0.5),
(4,13,'Audit, Compliance, and Risk Management',0.7),
(4,14,'Compensation Policy and Performance Incentives',0.9),
(4,15,'Transparency and Accountability',0.5),
(4,16,'Shareholder Rights and Corporate Governance',0.5);


