DROP TABLE IF EXISTS indicators;
CREATE TABLE indicators (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    metric_id INTEGER NOT NULL
);

INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 1);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 2);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 9);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 31);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 32);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 33);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 34);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 65);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 66);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 68);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 83);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 95);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 96);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 74);
INSERT INTO indicators (name, metric_id) VALUES ('Carbon Emissions and Air Pollutants', 88);
INSERT INTO indicators (name, metric_id) VALUES ('Energy Consumption and Electricity Consumption', 48);
INSERT INTO indicators (name, metric_id) VALUES ('Energy Consumption and Electricity Consumption', 49);
INSERT INTO indicators (name, metric_id) VALUES ('Energy Consumption and Electricity Consumption', 43);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 80);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 81);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 82);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 93);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 16);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 52);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 56);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 97);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 98);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 99);
INSERT INTO indicators (name, metric_id) VALUES ('Renewable Energy and Waste', 86);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 100);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 102);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 101);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 79);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 89);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 47);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 50);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 51);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 42);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 85);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 78);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 91);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 67);
INSERT INTO indicators (name, metric_id) VALUES ('Water Withdrawal and Sustainable Practices', 62);
INSERT INTO indicators (name, metric_id) VALUES ('Biodiversity and Climate Change Management', 24);
INSERT INTO indicators (name, metric_id) VALUES ('Biodiversity and Climate Change Management', 30);
INSERT INTO indicators (name, metric_id) VALUES ('Biodiversity and Climate Change Management', 64);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 57);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 58);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 59);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 77);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 53);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 104);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 105);
INSERT INTO indicators (name, metric_id) VALUES ('Human Rights and Gender Equality', 87);
INSERT INTO indicators (name, metric_id) VALUES ('Employee Well-being and Safety', 45);
INSERT INTO indicators (name, metric_id) VALUES ('Employee Well-being and Safety', 46);
INSERT INTO indicators (name, metric_id) VALUES ('Employee Well-being and Safety', 63);
INSERT INTO indicators (name, metric_id) VALUES ('Employee Well-being and Safety', 41);
INSERT INTO indicators (name, metric_id) VALUES ('Employee Well-being and Safety', 103);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 70);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 71);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 72);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 73);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 75);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 76);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 60);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 37);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 38);
INSERT INTO indicators (name, metric_id) VALUES ('Ethical Practices and Compliance', 55);
INSERT INTO indicators (name, metric_id) VALUES ('Certifications', 61);
INSERT INTO indicators (name, metric_id) VALUES ('Certifications', 20);
INSERT INTO indicators (name, metric_id) VALUES ('Certifications', 84);
INSERT INTO indicators (name, metric_id) VALUES ('Labor Relations and Employee Engagement', 92);
INSERT INTO indicators (name, metric_id) VALUES ('Labor Relations and Employee Engagement', 94);
INSERT INTO indicators (name, metric_id) VALUES ('Labor Relations and Employee Engagement', 90);
INSERT INTO indicators (name, metric_id) VALUES ('Corporate Social Responsibility (CSR) and Diversity', 15);
INSERT INTO indicators (name, metric_id) VALUES ('Corporate Social Responsibility (CSR) and Diversity', 69);
INSERT INTO indicators (name, metric_id) VALUES ('Board Structure and Independence', 4);
INSERT INTO indicators (name, metric_id) VALUES ('Board Structure and Independence', 5);
INSERT INTO indicators (name, metric_id) VALUES ('Board Structure and Independence', 10);
INSERT INTO indicators (name, metric_id) VALUES ('Board Structure and Independence', 13);
INSERT INTO indicators (name, metric_id) VALUES ('Board Structure and Independence', 11);
INSERT INTO indicators (name, metric_id) VALUES ('Audit, Compliance, and Risk Management', 3);
INSERT INTO indicators (name, metric_id) VALUES ('Audit, Compliance, and Risk Management', 6);
INSERT INTO indicators (name, metric_id) VALUES ('Audit, Compliance, and Risk Management', 12);
INSERT INTO indicators (name, metric_id) VALUES ('Audit, Compliance, and Risk Management', 18);
INSERT INTO indicators (name, metric_id) VALUES ('Audit, Compliance, and Risk Management', 26);
INSERT INTO indicators (name, metric_id) VALUES ('Compensation Policy and Performance Incentives', 7);
INSERT INTO indicators (name, metric_id) VALUES ('Compensation Policy and Performance Incentives', 8);
INSERT INTO indicators (name, metric_id) VALUES ('Compensation Policy and Performance Incentives', 21);
INSERT INTO indicators (name, metric_id) VALUES ('Compensation Policy and Performance Incentives', 28);
INSERT INTO indicators (name, metric_id) VALUES ('Compensation Policy and Performance Incentives', 29);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 14);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 22);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 23);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 25);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 35);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 36);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 39);
INSERT INTO indicators (name, metric_id) VALUES ('Transparency and Accountability', 40);
INSERT INTO indicators (name, metric_id) VALUES ('Shareholder Rights and Corporate Governance', 17);
INSERT INTO indicators (name, metric_id) VALUES ('Shareholder Rights and Corporate Governance', 19);
INSERT INTO indicators (name, metric_id) VALUES ('Shareholder Rights and Corporate Governance', 27);
INSERT INTO indicators (name, metric_id) VALUES ('Shareholder Rights and Corporate Governance', 44);
INSERT INTO indicators (name, metric_id) VALUES ('Shareholder Rights and Corporate Governance', 54);
