CREATE TABLE metric_weights (
    indicator_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    metric_id INTEGER NOT NULL
    year INTEGER,
    weight FLOAT NOT NULL
);

-- 插入指标名称和编号数据
INSERT INTO metric_weights (indicator_name, name, weight) VALUES 
('Carbon Emissions and Air Pollutants', 'AIRPOLLUTANTS_DIRECT', 0.017),
('Carbon Emissions and Air Pollutants', 'AIRPOLLUTANTS_INDIRECT', 0.017),
('Carbon Emissions and Air Pollutants', 'CO2DIRECTSCOPE1', 0.017),
('Carbon Emissions and Air Pollutants', 'CO2INDIRECTSCOPE2', 0.017),
('Carbon Emissions and Air Pollutants', 'CO2INDIRECTSCOPE3', 0.017),
('Carbon Emissions and Air Pollutants', 'CO2_NO_EQUIVALENTS', 0.017),
('Carbon Emissions and Air Pollutants', 'NOXEMISSIONS', 0.017),
('Carbon Emissions and Air Pollutants', 'N_OXS_OX_EMISSIONS_REDUCTION', 0.017),
('Carbon Emissions and Air Pollutants', 'PARTICULATE_MATTER_EMISSIONS', 0.017),
('Carbon Emissions and Air Pollutants', 'VOCEMISSIONS', 0.017),
('Carbon Emissions and Air Pollutants', 'VOC_EMISSIONS_REDUCTION', 0.017),
('Carbon Emissions and Air Pollutants', 'POLICY_EMISSIONS', 0.017),
('Carbon Emissions and Air Pollutants', 'TARGETS_EMISSIONS', 0.017),
('Carbon Emissions and Air Pollutants', 'TARGETS_WATER_EFFICIENCY', 0.017),
('Carbon Emissions and Air Pollutants', 'TARGETS_DIVERSITY_OPPORTUNITY', 0.017),
('Energy Consumption and Electricity Consumption', 'ENERGYUSETOTAL', 0.01),
('Energy Consumption and Electricity Consumption', 'ENERGYPURCHASEDDIRECT', 0.01),
('Renewable Energy and Waste', 'RENEWENERGYCONSUMED', 0.008),
('Renewable Energy and Waste', 'RENEWENERGYPRODUCED', 0.008),
('Renewable Energy and Waste', 'RENEWENERGYPURCHASED', 0.008),
('Renewable Energy and Waste', 'TRANALYTICRENEWENERGYUSE', 0.008),
('Renewable Energy and Waste', 'WASTE_RECYCLED', 0.008),
('Renewable Energy and Waste', 'WASTE_REDUCTION_TOTAL', 0.008),
('Renewable Energy and Waste', 'WASTETOTAL', 0.008),
('Renewable Energy and Waste', 'E_WASTE_REDUCTION', 0.008),
('Water Withdrawal and Sustainable Practices', 'WATERWITHDRAWALTOTAL', 0.008),
('Water Withdrawal and Sustainable Practices', 'WATER_TECHNOLOGIES', 0.008),
('Water Withdrawal and Sustainable Practices', 'WATER_USE_PAI_M10', 0.008),
('Water Withdrawal and Sustainable Practices', 'POLICY_WATER_EFFICIENCY', 0.008),
('Water Withdrawal and Sustainable Practices', 'TARGETS_WATER_EFFICIENCY', 0.008),
('Water Withdrawal and Sustainable Practices', 'POLICY_SUSTAINABLE_PACKAGING', 0.008),
('Water Withdrawal and Sustainable Practices', 'POLICY_WATER_EFFICIENCY', 0.008),
('Water Withdrawal and Sustainable Practices', 'POLICY_WATER_EFFICIENCY', 0.008),
('Water Withdrawal and Sustainable Practices', 'POLICY_WATER_EFFICIENCY', 0.008),
('Biodiversity and Climate Change Management', 'BIODIVERSITY_IMPACT_REDUCTION', 0.007),
('Biodiversity and Climate Change Management', 'CLIMATE_CHANGE_RISKS_OPP', 0.007),
('Biodiversity and Climate Change Management', 'NATURAL_RESOURCE_USE_DIRECT', 0.007),
('Human Rights and Gender Equality', 'GENDER_PAY_GAP_PERCENTAGE', 0.005),
('Human Rights and Gender Equality', 'HUMAN_RIGHTS_CONTRACTOR', 0.005),
('Human Rights and Gender Equality', 'HUMAN_RIGHTS_POLICY_DUEDILIGENCE', 0.005),
('Human Rights and Gender Equality', 'HUMAN_RIGHTS_VIOLATION_PAI', 0.005),
('Human Rights and Gender Equality', 'WOMENEMPLOYEES', 0.005),
('Human Rights and Gender Equality', 'WOMENMANAGERS', 0.005),
('Employee Well-being and Safety', 'EMPLOYEEFATALITIES', 0.006),
('Employee Well-being and Safety', 'EMPLOYEE_HEALTH_SAFETY_POLICY', 0.006),
('Employee Well-being and Safety', 'LOSTWORKINGDAYS', 0.006),
('Employee Well-being and Safety', 'WHISTLEBLOWER_PROTECTION', 0.006),
('Employee Well-being and Safety', 'TURNOVEREMPLOYEES', 0.006),
('Ethical Practices and Compliance', 'POLICY_BRIBERYAND_CORRUPTION', 0.01),
('Ethical Practices and Compliance', 'POLICY_BUSINESS_ETHICS', 0.01),
('Ethical Practices and Compliance', 'POLICY_CHILD_LABOR', 0.01),
('Ethical Practices and Compliance', 'POLICY_DATA_PRIVACY', 0.01),
('Ethical Practices and Compliance', 'POLICY_FORCED_LABOR', 0.01),
('Ethical Practices and Compliance', 'POLICY_FREEDOMOF_ASSOCIATION', 0.01),
('Ethical Practices and Compliance', 'POLICY_HUMAN_RIGHTS', 0.01),
('Ethical Practices and Compliance', 'POLICY_SUSTAINABLE_PACKAGING', 0.01),
('Ethical Practices and Compliance', 'CONFORMANCE_OECD_MNE', 0.01),
('Ethical Practices and Compliance', 'CONFORMANCE_UN_GUID', 0.01),
('Ethical Practices and Compliance', 'GRIEVANCE_REPORTING_PROCESS', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'ANIMAL_TESTING_REDUCTION', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'BRIBERY_AND_CORRUPTION_PAI_INSUFFICIENT_ACTIONS', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'CSR_REPORTINGGRI', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'CSR_REPORTING_EXTERNAL_AUDIT', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'GLOBAL_COMPACT', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'ISO14000', 0.01),
('Environmental and Social Governance (ESG) Standards and Certifications', 'SUPPLY_CHAINHS_POLICY', 0.01),
('Labor Relations and Employee Engagement', 'CEO_ANNUAL_COMPENSATION', 0.01),
('Labor Relations and Employee Engagement', 'CEO_PAY_RATIO_MEDIAN', 0.01),
('Labor Relations and Employee Engagement', 'TRADEUNIONREP', 0.01),
('Corporate Social Responsibility (CSR) and Diversity', 'ANNUAL_MEDIAN_COMPENSATION', 0.01),
('Corporate Social Responsibility (CSR) and Diversity', 'CONFORMANCE_UN_GUID', 0.01),
('Board Structure and Independence', 'ANALYTICBOARDFEMALE', 0.016),
('Board Structure and Independence', 'ANALYTICCEO_CHAIRMAN_SEPARATION', 0.016),
('Board Structure and Independence', 'ANALYTICCOMPCOMMIND', 0.016),
('Board Structure and Independence', 'ANALYTICCSR_COMP_INCENTIVES', 0.016),
('Board Structure and Independence', 'ANALYTICEMPLOYMENTCREATION', 0.016),
('Board Structure and Independence', 'ANALYTICINDEPBOARD', 0.016),
('Board Structure and Independence', 'ANALYTICNOMINATIONCOMMIND', 0.016),
('Board Structure and Independence', 'ANALYTICNONAUDITAUDITFEESRATIO', 0.016),
('Board Structure and Independence', 'ANALYTICNONEXECBOARD', 0.016),
('Board Structure and Independence', 'ANALYTICQMS', 0.016),
('Board Structure and Independence', 'ANALYTICTOTALDONATIONS', 0.016),
('Board Structure and Independence', 'ANALYTICWASTERECYCLINGRATIO', 0.016),
('Board Structure and Independence', 'ANALYTIC_ANTI_TAKEOVER_DEVICES', 0.016),
('Board Structure and Independence', 'ANALYTIC_AUDIT_COMM_EXPERTISE', 0.016),
('Board Structure and Independence', 'ANALYTIC_VOTING_RIGHTS', 0.016),
('Audit, Compliance, and Risk Management', 'ANALYTICAUDITCOMMIND', 0.01),
('Audit, Compliance, and Risk Management', 'CALL_MEETINGS_LIMITED_RIGHTS', 0.01),
('Audit, Compliance, and Risk Management', 'POLICY_DATA_PRIVACY', 0.01),
('Audit, Compliance, and Risk Management', 'POLICY_WHISTLEBLOWER_PROTECTION', 0.01),
('Audit, Compliance, and Risk Management', 'BRIBERY_AND_CORRUPTION_PAI_INSUFFICIENT_ACTIONS', 0.01),
('Compensation Policy and Performance Incentives', 'POLICY_BUSINESS_ETHICS', 0.006),
('Compensation Policy and Performance Incentives', 'POLICY_CHILD_LABOR', 0.006),
('Compensation Policy and Performance Incentives', 'POLICY_DATA_PRIVACY', 0.006),
('Compensation Policy and Performance Incentives', 'POLICY_FORCED_LABOR', 0.006),
('Compensation Policy and Performance Incentives', 'POLICY_FREEDOMOF_ASSOCIATION', 0.006),
('Transparency and Accountability', 'POLICY_BUSINESS_ETHICS', 0.006),
('Transparency and Accountability', 'POLICY_CHILD_LABOR', 0.006),
('Transparency and Accountability', 'POLICY_DATA_PRIVACY', 0.006),
('Transparency and Accountability', 'POLICY_FORCED_LABOR', 0.006),
('Transparency and Accountability', 'POLICY_FREEDOMOF_ASSOCIATION', 0.006),
('Transparency and Accountability', 'POLICY_HUMAN_RIGHTS', 0.006),
('Transparency and Accountability', 'POLICY_SUSTAINABLE_PACKAGING', 0.006),
('Shareholder Rights and Corporate Governance', 'ELIMINATION_CUM_VOTING_RIGHTS', 0.008),
('Shareholder Rights and Corporate Governance', 'POLICY_ANTI_TAKEOVER_DEVICES', 0.008),
('Shareholder Rights and Corporate Governance', 'POLICY_VOTING_RIGHTS', 0.008),
('Shareholder Rights and Corporate Governance', 'POLICY_WHISTLEBLOWER_PROTECTION', 0.008),
('Shareholder Rights and Corporate Governance', 'POLICY_SHAREHOLDER_RIGHTS', 0.008);

